# Generated by Django 5.1.3 on 2024-11-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='otac',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='otac_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
