# Generated by Django 5.1.3 on 2024-11-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_employee_otac_employee_otac_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='otac',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
