# Generated by Django 5.1.3 on 2024-11-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_employee_otac'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
