# Generated by Django 5.1.3 on 2024-11-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_employee_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_verified',
            new_name='verified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='otac',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='otac_expiry',
        ),
    ]
