# Generated by Django 5.1.3 on 2024-11-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_employee_user_employee_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='user',
        ),
    ]
