# Generated by Django 5.1.3 on 2024-12-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_amount_allowance_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='calculation_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='calculation_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10),
        ),
    ]
