# Generated by Django 5.1.3 on 2024-12-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_allowance_calculation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='calculation_type',
            field=models.CharField(choices=[('percentage ', '% of Base Salary'), ('fixed', 'Fixed Amount')], max_length=20),
        ),
    ]
