# Generated by Django 5.1.3 on 2024-12-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_allowance_calculation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='calculation_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10),
        ),
    ]
