# Generated by Django 5.1.3 on 2024-12-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_allowance_calculation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowance',
            name='job_group',
        ),
        migrations.AddField(
            model_name='allowance',
            name='job_groups',
            field=models.ManyToManyField(related_name='allowances', to='management.jobgroup'),
        ),
    ]
