# Generated by Django 5.1.3 on 2024-12-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_remove_allowance_job_group_allowance_job_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='job_group',
        ),
        migrations.AddField(
            model_name='deduction',
            name='job_groups',
            field=models.ManyToManyField(related_name='deductions', to='management.jobgroup'),
        ),
    ]
