# Generated by Django 5.1.3 on 2024-12-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_remove_deduction_job_group_deduction_job_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='calculation_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=15),
        ),
    ]
