# Generated by Django 5.1.3 on 2024-12-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowance',
            old_name='value',
            new_name='default_value',
        ),
        migrations.RenameField(
            model_name='deduction',
            old_name='value',
            new_name='default_value',
        ),
        migrations.RemoveField(
            model_name='allowance',
            name='job_groups',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='job_groups',
        ),
        migrations.AlterField(
            model_name='allowance',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='JobGroupAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.allowance')),
                ('job_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.jobgroup')),
            ],
            options={
                'unique_together': {('job_group', 'allowance')},
            },
        ),
        migrations.AddField(
            model_name='jobgroup',
            name='allowances',
            field=models.ManyToManyField(related_name='job_groups', through='management.JobGroupAllowance', to='management.allowance'),
        ),
        migrations.CreateModel(
            name='JobGroupDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.deduction')),
                ('job_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.jobgroup')),
            ],
            options={
                'unique_together': {('job_group', 'deduction')},
            },
        ),
        migrations.AddField(
            model_name='jobgroup',
            name='deductions',
            field=models.ManyToManyField(related_name='job_groups', through='management.JobGroupDeduction', to='management.deduction'),
        ),
    ]
