# Generated by Django 5.1.3 on 2024-12-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_rename_value_allowance_default_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobgroupallowance',
            name='calculation_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='fixed', max_length=15),
        ),
        migrations.AddField(
            model_name='jobgroupdeduction',
            name='calculation_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='fixed', max_length=15),
        ),
    ]
