# Generated by Django 5.1.3 on 2024-12-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_jobgroupallowance_calculation_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='location',
            new_name='address',
        ),
    ]
