# Generated by Django 5.1.3 on 2024-12-09 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_rename_location_branch_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.jobgroup'),
        ),
    ]
