# Generated by Django 5.1.3 on 2025-02-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_remove_allowance_calculation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='calculation_type',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='default_value',
        ),
    ]
